# Generated by Django 4.2.7 on 2023-11-21 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('psu_id', models.CharField(max_length=11, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('division_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_students.division')),
            ],
        ),
    ]
