# Generated by Django 4.2.7 on 2023-11-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_students', '0002_favoritesub'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='favorite_subject',
            field=models.ManyToManyField(to='app_students.favoritesub'),
        ),
    ]
